### ISSUE TITLE
Unable to set up emails with Celery

### ISSUE THREAD

**Issue by igorgolebiewski** [Flask-Middleware/flask-security#456]
Hi, 
while following the method explained in the docs to set up emails with Celery I encountered two issues (in stable version 4.0.0). 

Firstly, when providing my own implementation of the MailUtil class:

```
from flask_security import MailUtil

class MyMailUtil(MailUtil):
    def send_mail(self, template, subject, recipient, sender, body, html, user, **kwargs):
        send_flask_mail.delay(
            subject=subject,
            sender=sender,
            recipients=recipients,
            body=body,
            html=html,
        ) 
```

Celery throws an exception:
```
Traceback (most recent call last):
  File "c:\users\igorg\desktop\t4\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "c:\users\igorg\desktop\t4\venv\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "c:\users\igorg\desktop\t4\venv\lib\site-packages\flask_mail.py", line 181, in send
    if message.has_bad_headers():
  File "c:\users\igorg\desktop\t4\venv\lib\site-packages\flask_mail.py", line 400, in has_bad_headers
    headers = [self.sender, self.reply_to] + self.recipients
TypeError: can only concatenate list (not "str") to list
```
I added a helper list in send_mail definition, appended "recipient" arg, passed the list to send_flask_mail (instead of "recipients") and this made the problem go away. 

But then we get to the second issue, Celery throws the following exception:
```
Traceback (most recent call last):
  File "c:\users\igorg\desktop\t4\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "c:\users\igorg\desktop\t4\venv\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "c:\users\igorg\desktop\t4\venv\lib\site-packages\flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "C:\Python38\lib\smtplib.py", line 856, in sendmail
    self.ehlo_or_helo_if_needed()
  File "C:\Python38\lib\smtplib.py", line 604, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "C:\Python38\lib\smtplib.py", line 444, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "C:\Python38\lib\smtplib.py", line 371, in putcmd
    self.send(str)
  File "C:\Python38\lib\smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\igorg\desktop\t4\venv\lib\site-packages\celery\app\trace.py", line 405, in trace_task
    R = retval = fun(*args, **kwargs)
  File "C:\Users\igorg\Desktop\T4\app\celery_utils.py", line 7, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "c:\users\igorg\desktop\t4\venv\lib\site-packages\celery\app\trace.py", line 697, in __protected_call__
    return self.run(*args, **kwargs)
  File "C:\Users\igorg\Desktop\T4\app\__init__.py", line 48, in send_flask_mail
    mail.send(Message(**kwargs))
  File "c:\users\igorg\desktop\t4\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "c:\users\igorg\desktop\t4\venv\lib\site-packages\flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "C:\Python38\lib\smtplib.py", line 988, in quit
    res = self.docmd("quit")
  File "C:\Python38\lib\smtplib.py", line 424, in docmd
    self.putcmd(cmd, args)
  File "C:\Python38\lib\smtplib.py", line 371, in putcmd
    self.send(str)
  File "C:\Python38\lib\smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
```
Note, Flask-Mail setup seems to be correct, everything was working all right prior to attempting to get emails through Celery.

**Comment by jwag956** [comment]
Took me a couple days to spin up a celery repro. The first issue is a documentation one - should be:
recipients=[recipient],

I'll fix the docs.
I couldn't repro your second error. I used sqlite as a broker

```

import threading
import time
import flask
from flask import Flask, render_template_string, request
from flask_sqlalchemy import SQLAlchemy
from flask_security import Security, SQLAlchemyUserDatastore, \
    UserMixin, RoleMixin, login_required, roles_required, verify_password
from flask_security.models import fsqla_v2 as fsqla
from flask_security import MailUtil
from celery import Celery
from flask_mail import Message, Mail


class MyMailUtil(MailUtil):

    def send_mail(self, template, subject, recipient, sender, body, html, user,
                  **kwargs):
        send_flask_mail.delay(
            subject=subject,
            sender=sender,
            recipients=[recipient],
            body=body,
            html=html,
        )

# Create app
app = Flask(__name__)
app.config['DEBUG'] = True
app.config['SECRET_KEY'] = 'super-secret'
app.config['SECURITY_PASSWORD_SALT'] = 'super-secret-salt'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///mdb.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# flask-email
app.config['MAIL_SERVER'] = "smtp.zoho.com"
app.config['MAIL_PORT'] = 587
app.config['MAIL_USE_TLS'] = True
app.config['MAIL_USE_SSL'] = False
app.config['MAIL_USERNAME'] = "not-really-my-username"
app.config['MAIL_PASSWORD'] = "not-really-my-password"
# MAIL_DEBUG = True
app.config['MAIL_DEFAULT_SENDER'] = "sywapp@sywphoto.com"

# Create database connection object
db = SQLAlchemy(app)
# Define models
fsqla.FsModels.set_db_info(db)


class Role(db.Model, fsqla.FsRoleMixin):
    pass


class User(db.Model, fsqla.FsUserMixin):
    pass


# Setup Flask-Security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore, mail_util_cls=MyMailUtil)
mail = Mail(app)
celery = Celery(broker='sqla+sqlite:///celery.sqlite',
                backend='db+sqlite:///celery.sqlite')


def run_worker():
    celery.worker_main(['worker'])


@celery.task
def send_flask_mail(**kwargs):
    with app.app_context():
        mail.send(Message(**kwargs))


t = threading.Thread(target=run_worker)
t.setDaemon(True)
t.start()

security._mail_util.send_mail(None, 'Hi from celery', 'jwag.wagner@gmail.com',
                              'sywapp@sywphoto.com', 'short message', None, None)

time.sleep(5)
```
