### ISSUE TITLE
App Context error

### ISSUE THREAD

**Issue by alieksie** [Flask-Middleware/flask-security#521]
With Flask 2.0.1 got the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 990, in main
    cli.main(args=sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 845, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 321, in __init__
    self._load_unlocked()
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 346, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 406, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 256, in locate_app
    __import__(module_name)
  File "/app/app.py", line 15, in <module>
    app = create_app(settings)
  File "/app/startup/app.py", line 35, in create_app
    setup_app(app, custom_injector, injector_modules)
  File "/app/startup/app.py", line 70, in setup_app
    FlaskInjector(app=app, injector=custom_injector, modules=modules.values())
  File "/usr/local/lib/python3.7/site-packages/flask_injector/__init__.py", line 327, in __init__
    process_dict(container, injector)
  File "/usr/local/lib/python3.7/site-packages/flask_injector/__init__.py", line 382, in process_dict
    process_dict(value, injector)
  File "/usr/local/lib/python3.7/site-packages/flask_injector/__init__.py", line 379, in process_dict
    elif hasattr(value, '__call__'):
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 422, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 544, in _get_current_object
    return self.__local()  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/flask_security/core.py", line 211, in <lambda>
    lambda: current_app.config.get("MAIL_DEFAULT_SENDER", "no-reply@localhost")
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 422, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 544, in _get_current_object
    return self.__local()  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/flask/globals.py", line 47, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.
```

Most probably due to line in flask_securiyt core

```
"EMAIL_SENDER": LocalProxy(
        lambda: current_app.config.get("MAIL_DEFAULT_SENDER", "no-reply@localhost")
    ),
```

The easiest fix would be just to default it to "no-reply@localhost"

UPD: looked more closely and might be that Flask-Injector is trying to iterate over config dict values

**Comment by jwag956** [comment]
Yup - that's not really best practice for flask - most everything needs an app context. Of course for your application you can set the EMAIL_SENDER config to a static string.
