### ISSUE TITLE
Quickstart example not working

### ISSUE THREAD

**Issue by ekw** [Flask-Middleware/flask-security#579]
I am trying the "Basic SQLAlchemy Application with session" quickstart example here: 
https://flask-security-too.readthedocs.io/en/stable/quickstart.html#basic-sqlalchemy-application-with-session

I copied and pasted the 3 files (app.py, database.py, models.py) directly from that webpage.

I run **_python app.py_** and when I browse to the server, I get this:

```
Traceback (most recent call last):
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask/app.py", line 1511, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask/app.py", line 1563, in try_trigger_before_first_request_functions
    self.ensure_sync(func)()
  File "/opt/virtualenvs/test/project/app.py", line 28, in create_user
    user_datastore.create_user(email="test@me.com", password=hash_password("password"))
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask_security/datastore.py", line 398, in create_user
    user = self.user_model(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'fs_uniquifier'
```

I am using python 3.8.10 and
Flask==2.0.3
Flask-Security-Too==4.1.2
Flask-Login==0.5.0
Flask-Principal==0.4.0
Flask-WTF==1.0.0
Flask-SQLAlchemy==2.5.1
SQLAlchemy==1.4.31
email-validator==1.1.3
itsdangerous==2.0.1
passlib==1.7.4
blinker==1.4

Thanks in advance for any help/suggestions.

**Comment by jwag956** [comment]
I just tried the same exercise and am not seeing that error (I am seeing some sqlite  threading error which I am not sure whats going on) but the app works and I can log in as test@me.com

My guess is somewhere you copied an older version of the quickstart guide that doesn't have that field in the models.
