### ISSUE TITLE
bleach module needed when logging in with username

### ISSUE THREAD

**Issue by ekw** [Flask-Middleware/flask-security#580]
When I tried to login with username (vs. email address), I got this exception:
```
[2022-02-21 09:57:14 +0000] [593558] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask_security/decorators.py", line 436, in decorated
    return fn(*args, **kwargs)
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask_security/views.py", line 162, in login
    if form.validate_on_submit():
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask_security/forms.py", line 450, in validate
    self.user = find_user(self.email.data)
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask_security/utils.py", line 827, in find_user
    idata = details["mapper"](identity)
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask_security/utils.py", line 872, in uia_username_mapper
    return _security._username_util.normalize(identity)
  File "/opt/virtualenvs/test/lib/python3.8/site-packages/flask_security/username_util.py", line 61, in normalize
    import bleach
ModuleNotFoundError: No module named 'bleach'
```

I had to **pip install bleach** to fix.  Should the bleach module be listed/installed as a dependency for flask-security-too?

**Comment by jwag956** [comment]
Good point - it shouldn't be a strict dependency since it is only needed if using the default username_util implementation. I'll add some documentation to USERNAME_ENABLE to make that clearer, and maybe install it as part of 'common' pip extras.

thanks for the report.
