### ISSUE TITLE
roles_users table and schema names

### ISSUE THREAD

**Issue by karres-illinois** [Flask-Middleware/flask-security#631]
Hi

In the User and Role example model classes ([https://flask-security-too.readthedocs.io/en/stable/quickstart.html#basic-sqlalchemy-application-with-session](https://flask-security-too.readthedocs.io/en/stable/quickstart.html#basic-sqlalchemy-application-with-session)) there is an SQLAlchemy "association Object ([https://docs.sqlalchemy.org/en/14/orm/basic_relationships.html#association-object](https://docs.sqlalchemy.org/en/14/orm/basic_relationships.html#association-object)) table `roles_users`.

Does Flask-Security-Too *require* this version of linking tables?  If I create parent/child relationships differently should that matter?

Also, my target database is on an existing MS SQL Server.  The "database" exists and I must use an existing "schema".  Will using 

`__table_args__ = {"schema": "MySchema"}`

in my model classes impact the User and Role classes?

Thanks

**Comment by jwag956** [comment]
I don't think there is any issue with having your own schema name - and you can change the name of the tables as well.

As for requiring that precise way of linking tables - no - FS doesn't require that - in fact other DBs - such as mongoDB use a different method altogether.

Basically - FS will dereference user.roles and expect a list of role objects.

Feel free to add issues you are encountering.

**Comment by karres-illinois** [comment]
Thank you,

I started out trying to follow the sample code with a session but decided to change the relationship method to remove the linking table.  I have successfully run `flask db init` and am trying to run the first `flask db migrate` but get the error:

	(venv) PS C:\Users\me\PycharmProjects\MyProject\UserInterface\MyApp> flask db migrate
	INFO  [alembic.runtime.migration] Context impl MSSQLImpl.
	INFO  [alembic.runtime.migration] Will assume transactional DDL.
	Traceback (most recent call last):
	  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
		return _run_code(code, main_globals, None,
	  File "C:\Python310\lib\runpy.py", line 86, in _run_code
		exec(code, run_globals)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\Scripts\flask.exe\__main__.py", line 7, in <module>
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\flask\cli.py", line 988, in main
		cli.main()
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\flask\cli.py", line 579, in main
		return super().main(*args, **kwargs)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\click\core.py", line 1055, in main
		rv = self.invoke(ctx)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\click\core.py", line 1657, in invoke
		return _process_result(sub_ctx.command.invoke(sub_ctx))
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\click\core.py", line 1657, in invoke
		return _process_result(sub_ctx.command.invoke(sub_ctx))
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\click\core.py", line 1404, in invoke
		return ctx.invoke(self.callback, **ctx.params)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\click\core.py", line 760, in invoke
		return __callback(*args, **kwargs)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\click\decorators.py", line 26, in new_func
		return f(get_current_context(), *args, **kwargs)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\flask\cli.py", line 427, in decorator
		return __ctx.invoke(f, *args, **kwargs)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\click\core.py", line 760, in invoke
		return __callback(*args, **kwargs)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\flask_migrate\cli.py", line 104, in migrate
		_migrate(directory, message, sql, head, splice, branch_label, version_path,
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\flask_migrate\__init__.py", line 98, in wrapped
		f(*args, **kwargs)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\flask_migrate\__init__.py", line 155, in migrate
		command.revision(config, message, autogenerate=True, sql=sql,
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\alembic\command.py", line 229, in revision
		script_directory.run_env()
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\alembic\script\base.py", line 569, in run_env
		util.load_python_file(self.dir, "env.py")
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\alembic\util\pyfiles.py", line 94, in load_python_file
		module = load_module_py(module_id, path)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\alembic\util\pyfiles.py", line 110, in load_module_py
		spec.loader.exec_module(module)  # type: ignore
	  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
	  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\MyApp\migrations\env.py", line 104, in <module>
		run_migrations_online()
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\MyApp\migrations\env.py", line 98, in run_migrations_online
		context.run_migrations()
	  File "<string>", line 8, in run_migrations
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\alembic\runtime\environment.py", line 853, in run_migrations
		self.get_context().run_migrations(**kw)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\alembic\runtime\migration.py", line 611, in run_migrations
		for step in self._migrations_fn(heads, self):
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\alembic\command.py", line 205, in retrieve_migrations
		revision_context.run_autogenerate(rev, context)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\alembic\autogenerate\api.py", line 526, in run_autogenerate
		self._run_environment(rev, migration_context, True)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\alembic\autogenerate\api.py", line 573, in _run_environment
		compare._populate_migration_script(
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\alembic\autogenerate\compare.py", line 55, in _populate_migration_script
		_produce_net_changes(autogen_context, upgrade_ops)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\alembic\autogenerate\compare.py", line 89, in _produce_net_changes
		comparators.dispatch("schema", autogen_context.dialect.name)(
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\alembic\util\langhelpers.py", line 267, in go
		fn(*arg, **kw)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\alembic\autogenerate\compare.py", line 125, in _autogen_for_tables
		[(table.schema, table.name) for table in autogen_context.sorted_tables]
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1113, in __get__
		obj.__dict__[self.__name__] = result = self.fget(obj)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\alembic\autogenerate\api.py", line 443, in sorted_tables
		result.extend(m.sorted_tables)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 4697, in sorted_tables
		return ddl.sort_tables(
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\sqlalchemy\sql\ddl.py", line 1213, in sort_tables
		for (t, fkcs) in sort_tables_and_constraints(
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\sqlalchemy\sql\ddl.py", line 1291, in sort_tables_and_constraints
		dependent_on = fkc.referred_table
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 3808, in referred_table
		return self.elements[0].column.table
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1113, in __get__
		obj.__dict__[self.__name__] = result = self.fget(obj)
	  File "C:\Users\me\PycharmProjects\MyProject\UserInterface\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 2507, in column
		raise exc.NoReferencedTableError(
	sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'roles_users.role_id' could not find table 'role' with which to generate a foreign key to target column 'id'

The `User` and `Role` models look like (pruned for length):

	### USER
	#
	import uuid
	from flask_security import UserMixin
	from sqlalchemy import Column, Integer, String, Boolean, Unicode, DateTime, func
	from sqlalchemy.orm import relationship, backref
	from app.database import Base
	
	class User(Base, UserMixin):
		__tablename__ = 'user'
		__table_args__ = {"schema": "ExistingSchemaName"}

		id = Column(Integer,primary_key=True)
		email = Column(Unicode(255),nullable=False,server_default=u'',unique=True)
		...
		# Flask-Security-Too fields
		fs_uniquifier = Column(String(255), unique=True, nullable=False)
		confirmed_at = Column(DateTime())
		last_login_at = Column(DateTime())
		current_login_at = Column(DateTime())
		last_login_ip = Column(String(100))
		current_login_ip = Column(String(100))
		login_count = Column(Integer)

		# Relationships

		child_roles = relationship('Role',back_populates='parent_user')

	### ROLE
	#
	import uuid
	from flask_security import RoleMixin
	from sqlalchemy import Column, Integer, String, ForeignKey
	from sqlalchemy.orm import relationship
	from app.database import Base
	
	class Role(Base, RoleMixin):
		__tablename__ = 'role'
		__table_args__ = {"schema": "ExistingSchemaName"}

		id = Column(Integer(),primary_key=True)
		name = Column(String(64),nullable=False,server_default=u'',unique=True)
		description = Column(String(255),nullable=False,server_default=u'')

		# Have also tried adding schema name to ForeignKey without success, as in:
		# user_id = Column(Integer,ForeignKey("ExistingSchemaName.user.id"))
		user_id = Column(Integer,ForeignKey("user.id"))
		parent_user = relationship("User",back_populates="child_roles")

The `app.database.py` file looks like:

	from .settings import SQLALCHEMY_DATABASE_URI
	from sqlalchemy import create_engine
	from sqlalchemy.orm import scoped_session, sessionmaker
	from sqlalchemy.ext.declarative import declarative_base

	engine = create_engine(SQLALCHEMY_DATABASE_URI)
	db = scoped_session(
		sessionmaker(
			autocommit=False,
			autoflush=False,
			bind=engine
		)
	)

	Base = declarative_base()
	Base.query = db.query_property()


	def init_db():
		import app.models
		Base.metadata.create_all(bind=engine)

I think that I have set the one-to-many relationships correctly but I do not know what I am missing.

I have also tried the linking table version but end up with the same error on the first migration.  As far as I can tell the only place that references a table named `roles_users` is in the files under `venv/Lib/site-packages/flask_security/models` so I am not sure why anything would reference it?

**Comment by jwag956** [comment]
I probably replied too quickly - MANY to MANY is likely what is required - that precise  association table roles_users I don't believe is references anywhere inside FS. What does your alembic migrate scripts look like?

**Comment by karres-illinois** [comment]
If you mean the `env.py` script it is:

	import logging
	from logging.config import fileConfig

	from flask import current_app

	from alembic import context

	# this is the Alembic Config object, which provides
	# access to the values within the .ini file in use.
	config = context.config

	# Interpret the config file for Python logging.
	# This line sets up loggers basically.
	fileConfig(config.config_file_name)
	logger = logging.getLogger('alembic.env')

	# add your model's MetaData object here
	# for 'autogenerate' support
	# from myapp import mymodel
	# target_metadata = mymodel.Base.metadata
	config.set_main_option(
		'sqlalchemy.url',
		str(current_app.extensions['migrate'].db.get_engine().url).replace(
			'%', '%%'))
	target_metadata = current_app.extensions['migrate'].db.metadata


	# other values from the config, defined by the needs of env.py,
	# can be acquired:
	# my_important_option = config.get_main_option("my_important_option")
	# ... etc.

	def include_name(name, type_, parent_names):
		if type_ == "schema":
			return name in ["ExistingSchema"]
		else:
			return True


	def run_migrations_offline():
		"""Run migrations in 'offline' mode.

		This configures the context with just a URL
		and not an Engine, though an Engine is acceptable
		here as well.  By skipping the Engine creation
		we don't even need a DBAPI to be available.

		Calls to context.execute() here emit the given string to the
		script output.

		"""
		url = config.get_main_option("sqlalchemy.url")
		context.configure(
			url=url,
			target_metadata=target_metadata,
			literal_binds=True,
			version_table_schema='ExistingSchema',
			include_schemas=True,
			include_name=include_name
		)

		with context.begin_transaction():
			context.run_migrations()


	def run_migrations_online():
		"""Run migrations in 'online' mode.

		In this scenario we need to create an Engine
		and associate a connection with the context.

		"""

		# this callback is used to prevent an auto-migration from being generated
		# when there are no changes to the schema
		# reference: http://alembic.zzzcomputing.com/en/latest/cookbook.html
		def process_revision_directives(context, revision, directives):
			if getattr(config.cmd_opts, 'autogenerate', False):
				script = directives[0]
				if script.upgrade_ops.is_empty():
					directives[:] = []
					logger.info('No changes in schema detected.')

		connectable = current_app.extensions['migrate'].db.get_engine()

		with connectable.connect() as connection:
			context.configure(
				connection=connection,
				target_metadata=target_metadata,
				process_revision_directives=process_revision_directives,
				version_table_schema='ExistingSchema',
				include_schemas=True,
				include_name=include_name,
				**current_app.extensions['migrate'].configure_args
			)

			with context.begin_transaction():
				context.run_migrations()


	if context.is_offline_mode():
		run_migrations_offline()
	else:
		run_migrations_online()

**Comment by jwag956** [comment]
Unless you include those models - which it doesn't appear you are - those are just helpful mixins. Many FS tests don't use those at all and have models similar to your (but with the roles_users) table.

In terms of Alembic - I meant the migrations /folder - what is in there. I am a bit confused as to precisely what you are migrating from-to?

**Comment by karres-illinois** [comment]
migrations contains:

```
migrations
migrations/alembic.ini
migrations/env.py
migrations/README
migrations/script.py.mako
migrations/versions
migrations/__pycache__
migrations/__pycache__/env.cpython-310.pyc
```

Except for the `env.py`` file it is the result of the initial `flask db init`.

For the moment I am not migrating "from" anything.  I am starting fresh.  The old version was also a "test" install that used sqlite as the DB.  I was using Flask and Flask-User under Python 3.6 but there were some version issues.  Part of the 3.6 version of the app have to stay under 3.6 because of a third-party library that I have no control over.  I can "factor out" the user management part though and that is what brought me here.

**Comment by jwag956** [comment]
I am sort of at a loss - I assume you have deleted the DB and tried again - I wonder if somehow Alembic has found those model files?
