### ISSUE TITLE
Flask-Security error does not validate SQLite 'roles-users' relationship

### ISSUE THREAD

**Issue by ludiusvox** [Flask-Middleware/flask-security#681]
fsqla.FsModels.set_db_info(db)
    
        class Role(db.Model, fsqla.FsRoleMixin):
            pass

        class User(db.Model, fsqla.FsUserMixin):
            pass  
        user_datastore = SQLAlchemyUserDatastore(db, User, Role)
   
        
    
    #login_manager.login_view = '/login'
    security = Security(app, user_datastore,register_form=ExtendedRegisterForm)
  

the old code had a clause:
roles_users = db.Table('roles_users',
        db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
        db.Column('role_id', db.Integer(), db.ForeignKey('role.id')))

Traceback (most recent call last):
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: roles_users

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/flask_security/decorators.py", line 618, in wrapper
    return f(*args, **kwargs)
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/flask_security/views.py", line 307, in register
    if form.validate_on_submit():
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/flask_security/forms.py", line 645, in validate
    if not super().validate(**kwargs):
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/flask_security/forms.py", line 602, in validate
    if not super().validate(**kwargs):
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/wtforms/form.py", line 329, in validate
    return super().validate(extra)
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/wtforms/form.py", line 146, in validate
    if not field.validate(self, extra):
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/wtforms/fields/core.py", line 242, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/wtforms/fields/core.py", line 262, in _run_validation_chain
    validator(form, self)
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/flask_security/forms.py", line 191, in unique_user_email
    form.existing_email_user = _datastore.find_user(
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/flask_security/datastore.py", line 785, in find_user
    return query.filter(subquery).first()
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2823, in first
    return self.limit(1)._iter().first()
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
    result = self.session.execute(
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/aaronl/opt/anaconda3/envs/flaskEnv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: roles_users
[SQL: SELECT anon_1.user_id AS anon_1_user_id, anon_1.user_email AS anon_1_user_email, anon_1.user_active AS anon_1_user_active, anon_1.user_fs_uniquifier AS anon_1_user_fs_uniquifier, anon_1.user_confirmed_at AS anon_1_user_confirmed_at, anon_1.user_last_login_at AS anon_1_user_last_login_at, anon_1.user_current_login_at AS anon_1_user_current_login_at, anon_1.user_last_login_ip AS anon_1_user_last_login_ip, anon_1.user_current_login_ip AS anon_1_user_current_login_ip, anon_1.user_login_count AS anon_1_user_login_count, anon_1.user_tf_primary_method AS anon_1_user_tf_primary_method, anon_1.user_tf_totp_secret AS anon_1_user_tf_totp_secret, anon_1.user_tf_phone_number AS anon_1_user_tf_phone_number, anon_1.user_create_datetime AS anon_1_user_create_datetime, anon_1.user_update_datetime AS anon_1_user_update_datetime, anon_1.user_username AS anon_1_user_username, anon_1.user_us_totp_secrets AS anon_1_user_us_totp_secrets, anon_1.user_fs_webauthn_user_handle AS anon_1_user_fs_webauthn_user_handle, anon_1.user_mf_recovery_codes AS anon_1_user_mf_recovery_codes, anon_1.user_password AS anon_1_user_password, anon_1.user_us_phone_number AS anon_1_user_us_phone_number, role_1.id AS role_1_id, role_1.name AS role_1_name, role_1.description AS role_1_description, role_1.permissions AS role_1_permissions, role_1.update_datetime AS role_1_update_datetime 
FROM (SELECT user.id AS user_id, user.email AS user_email, user.active AS user_active, user.fs_uniquifier AS user_fs_uniquifier, user.confirmed_at AS user_confirmed_at, user.last_login_at AS user_last_login_at, user.current_login_at AS user_current_login_at, user.last_login_ip AS user_last_login_ip, user.current_login_ip AS user_current_login_ip, user.login_count AS user_login_count, user.tf_primary_method AS user_tf_primary_method, user.tf_totp_secret AS user_tf_totp_secret, user.tf_phone_number AS user_tf_phone_number, user.create_datetime AS user_create_datetime, user.update_datetime AS user_update_datetime, user.username AS user_username, user.us_totp_secrets AS user_us_totp_secrets, user.fs_webauthn_user_handle AS user_fs_webauthn_user_handle, user.mf_recovery_codes AS user_mf_recovery_codes, user.password AS user_password, user.us_phone_number AS user_us_phone_number 
FROM user 
WHERE lower(user.email) = lower(?)
 LIMIT ? OFFSET ?) AS anon_1 LEFT OUTER JOIN (roles_users AS roles_users_1 JOIN role AS role_1 ON role_1.id = roles_users_1.role_id) ON anon_1.user_id = roles_users_1.user_id]
[parameters: ('aaronclinder@outlook.com', 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

I am using fsqlaV3 I am not sure what to do since the Flask-Security framework is so rigid

**Comment by ludiusvox** [comment]
Yes I ended up reinstalling the entire framework from scratch, running the db.create_all() through the click command and got past this error.  SUCCESS after registration it is getting from the security.registration route to the dashboard route, which is good.  

Right now I am trying to get login route to "next" into a @loginrequired route, of any predetermined route, I will post back later thanks for your response.

It appears to check to see if password matches and I disabled Flask-Mail because I don't want to deal with email confirmation right now, but the problem that has been getting me stumped for days is:

`@bp_user.route('/blog', methods=['GET','POST'])
@login_required
def blog():
        return render_template("blog.html")`

I read something that says don't use `@login_required` but `@auth_required`  I am trying to get flask security to activate the "next" feature after login, I have a few usernames which validate now. Once I can log into protected views that's had me stumped for 4-5 days, thank you for your reply.

**Comment by jwag956** [comment]
Glad you are making progress. Doing the db.create_all() I usually do in my application based on whether I have the 'admin' user setup already - but using click is good also.

Yes - using @auth_required is better in order to be able to take advantage of all features - but @login_required is fine for getting started. the next parameter should just work i.e. if you send get('/login?next=/mypage') upon successful login it will redirect. If you just do get('/mypage') that is protected with @Login_required - you should see a redirect which includes (as the next parameter) your original url - you really shouldn't have to do anything.

**Comment by ludiusvox** [comment]
Okay so I got the full framework functioning last night but it did take me a week, there was a config file settings that made it a weird bug, so that I could register & then log in, but once I logged out, I couldn't log back in.  Since I have the solution I will post my settings so that other viewers can save some time getting the framework up and running (maybe I am slow but it took a full 4 evenings to get working)

SECURITY_EMAIL_VALIDATOR_ARGS = { "check_deliverability" : False }
    SECRET_KEY = os.environ.get('SECRET_KEY', '3nF3Rn0')
    APP_DIR = os.path.abspath(os.path.dirname(__file__))  # This directory
    PROJECT_ROOT = os.path.abspath(os.path.join(APP_DIR, os.pardir))
    DEBUG_TB_ENABLED = False  # Disable Debug toolbar
    DEBUG_TB_INTERCEPT_REDIRECTS = False
    CACHE_TYPE = 'simple'  # Can be "memcached", "redis", etc.
    SQLALCHEMY_DATABASE_URI = 'sqlite:///enferno.db'
    # for postgres
    #SQLALCHEMY_DATABASE_URI = os.environ.get('SQLALCHEMY_DATABASE_URI', 'postgresql:///enferno')
    SQLALCHEMY_TRACK_MODIFICATIONS = True

    #CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/10')
    #CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/11')
    SQLALCHEMY_RECORD_QUERIES = True
    TESTING = False
    DEBUG = True
    SECURITY_REGISTERABLE = True
    import os
    SECURITY_PASSWORD_SALT = os.environ.get("SECURITY_PASSWORD_SALT", '#############################################')
    import secrets
    #app.config['SECURITY_USER_IDENTITY_ATTRIBUTES'] = 'username'
    LOGIN_DISABLED = False
    #SECURITY_POST_LOGIN_VIEW = "login_user.html"
    secret = secrets.token_urlsafe(32)
    #app.config["SECRET_KEY"] = os.environ.get('SECRET_KEY', '##############')
    #app.config.from_object('config.email')
    secret_key = secret
    CACHE_NO_NULL_WARNING = True
    WTF_CSRF_CHECK_DEFAULT = False
    SECURITY_CSRF_IGNORE_UNAUTH_ENDPOINTS = False
    SECURITY_CSRF_COOKIE_NAME = "XSRF-TOKEN"
   # have session and remember cookie be samesite (flask/flask_login)
    REMEMBER_COOKIE_SAMESITE = "strict"
    SESSION_COOKIE_SAMESITE = "strict"
    SECURITY_RECOVERABLE = True
    SECURITY_TRACKABLE = True
    
    import logging, sys
    logging.basicConfig(stream=sys.stderr)
    SQLALCHEMY_TRACK_MODIFICATIONS = True
    SESSION_TYPE = 'filesystem'
    #app.config['SECURITY_EMAIL_SENDER'] = 'anyone@anywhere.com
    
    
    DEBUG_TB_INTERCEPT_REDIRECTS = False
    
    SQLALCHEMY_ENGINE_OPTIONS = {
    "pool_pre_ping": True,
    }

    # Mail Config
    SEND_REGISTEREMAIL = False
    # security
    SECURITY_REGISTERABLE = True
    SECURITY_RECOVERABLE = True
    SECURITY_CONFIRMABLE = False
    
    SECURITY_TRACKABLE = True
    SECURITY_PASSWORD_HASH = 'bcrypt'
    SECURITY_PASSWORD_SALT = os.environ.get('SECURITY_PASSWORD_SALT', '#######')
    SECURITY_USER_IDENTITY_ATTRIBUTES = [{"email": {"mapper": uia_username_mapper, "case_insensitive": True}}]
    
    
    SECURITY_POST_CONFIRM_VIEW = '/dashboard'
    POST_LOGIN_VIEW = '/login'
    #SESSION_TYPE = 'redis'
    #SESSION_REDIS = redis.from_url(os.environ.get('SESSION_REDIS', 'redis://localhost:6379/1'))
    PERMANENT_SESSION_LIFETIME = 3600
