### ISSUE TITLE
ValueError: Your login_form or register_form has a 'username' attribute already

### ISSUE THREAD

**Issue by catacal123** [Flask-Middleware/flask-security#740]
I am trying to use Flask-Security-Too 5.1.0 on my Flask webpage in Docker. I changed `SECURITY_USERNAME_ENABLE` to `True` and it gave me the ValueError. 
I am not using any custom templates or changing anything that would cause this error. 
When I change `SECURITY_USERNAME_ENABLE` to `False`, everything works fine as far as registration, logging in with email, etc.

Here is the complete Traceback:
```
booking-website-1   | Traceback (most recent call last):
booking-website-1   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
booking-website-1   |     worker.init_process()
booking-website-1   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
booking-website-1   |     self.load_wsgi()
booking-website-1   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
booking-website-1   |     self.wsgi = self.app.wsgi()
booking-website-1   |                 ^^^^^^^^^^^^^^^
booking-website-1   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
booking-website-1   |     self.callable = self.load()
booking-website-1   |                     ^^^^^^^^^^^
booking-website-1   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
booking-website-1   |     return self.load_wsgiapp()
booking-website-1   |            ^^^^^^^^^^^^^^^^^^^
booking-website-1   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
booking-website-1   |     return util.import_app(self.app_uri)
booking-website-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
booking-website-1   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 412, in import_app
booking-website-1   |     app = app(*args, **kwargs)
booking-website-1   |           ^^^^^^^^^^^^^^^^^^^^
booking-website-1   |   File "/booking/booking/app.py", line 84, in create_app
booking-website-1   |     app.security = Security(app, user_datastore)
booking-website-1   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
booking-website-1   |   File "/usr/local/lib/python3.11/site-packages/flask_security/core.py", line 1307, in __init__
booking-website-1   |     self.init_app(app, datastore, register_blueprint=register_blueprint)
booking-website-1   |   File "/usr/local/lib/python3.11/site-packages/flask_security/core.py", line 1483, in init_app
booking-website-1   |     raise ValueError(
booking-website-1   | ValueError: Your login_form or register_form has a 'username' attribute already
```

When I look in core.py I see the following code that causes the error:
```
            # if they want USERNAME_ENABLE - then they better not have defined
            # username in their own forms
            if any(
                hasattr(self.forms[f].cls, "username")
                for f in [
                    "register_form",
                    "confirm_register_form",
                    "login_form",
                ]
            ):  # pragma: no cover
                raise ValueError(
                    "Your login_form or register_form has a"
                    " 'username' attribute already"
                )
```

Is this error supposed to flag the templates supplied with Flask-Security? It appears that it is for me.

Thank you for your time.

**Comment by jwag956** [comment]
Not template - but form - are you sure you didn't define your own LoginForm?
Also - possibly - by any chance did you call init_app more than once?

I am not that familiar with gunicorn - any chance 2 threads both try to initialize Flask-Security?

**Comment by catacal123** [comment]
Hello jwag956,

The register and login template that come with Flask-Security-Too are in the "flask_security/templates/security" directory. The templates are named "register_form.html" and "login_form.html".

I did not call init_app on Security, I set it up per the Quick Start with Flask-SQLAlchemy.

I removed my container, images, and volumes and set gunicorn to use 1 thread, and it still does the same thing.

I appreciate your assistance with debugging this issue.

**Comment by catacal123** [comment]
Hello jwag956,

The register and login template that come with Flask-Security-Too are in the "flask_security/templates/security" directory. The templates are named "register_form.html" and "login_form.html".

I did not call init_app on Security, I set it up per the Quick Start with Flask-SQLAlchemy.

I removed my container, images, and volumes and set gunicorn to use 1 thread, and it still does the same thing.

I appreciate your assistance with debugging this issue.

**Comment by jwag956** [comment]
Can you share some initialization code and config? As I mentioned in my last note - this isn't about templates - it's about forms - those are 2 separate things.

**Comment by catacal123** [comment]
Sure, here are my configuration settings for Flask-Security-Too:
```
#Flask-Security
SECURITY_PASSWORD_SALT = os.environ.get("SECURITY_PASSWORD_SALT", '146585145368132386173505678016728509634')
REMEMBER_COOKIE_SAMESITE = "strict"
SESSION_COOKIE_SAMESITE = "strict"
SQLALCHEMY_ENGINE_OPTIONS = { "pool_pre_ping": True, }
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECURITY_USERNAME_ENABLE = False
SECURITY_CONFIRMABLE = False
SECURITY_REGISTERABLE = True
SECURITY_SEND_REGISTER_EMAIL = False
SEND_PASSWORD_RESET_NOTICE_EMAIL = False
SEND_PASSWORD_CHANGE_EMAIL = False
SECURITY_RECOVERABLE = True
SECURITY_CHANGEABLE = True
SECURITY_EMAIL_PLAINTEXT = False
SECURITY_EMAIL_HTML = True
SECURITY_PASSWORD_CHECK_BREACHED = None
SECURITY_PASSWORD_BREACHED_COUNT = 1
SECURITY_PASSWORD_COMPLEXITY_CHECKER = "zxcvbn"
```

Here is the website service in my docker-compose.yml file:
```
  website:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" --reload "booking.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/booking'
    ports:
      - '8000:8000'
```

Here is the create_app function, I initialize the user_datastore and Security in here:
```
def create_app(settings_override=None):
    """
    Create a Flask application using the app factory pattern.

    :param settings_override: Override settings
    :return: Flask app
    """
    app = Flask(__name__, static_folder="../public", static_url_path="")

    app.config.from_object("config.settings")

    if settings_override:
        app.config.update(settings_override)

    middleware(app)
    error_templates(app)
    exception_handler(app)
    app.register_blueprint(page)
    app.register_blueprint(up)
    app.register_blueprint(contact)
    extensions(app)
    register_cli_commands(app)

    user_datastore = SQLAlchemyUserDatastore(db, User, Role)
    app.security = Security(app, user_datastore)

    return app

```

**Comment by jwag956** [comment]
I will be AFK for a couple days - not sure what is going on - but flask security should allow for reinitializing with same config - I got a bit overzealous trying to protect apps from them selves 😎

Try just commenting out that code and see if everything works

**Comment by catacal123** [comment]
Thank you again for your assistance! I am going to leave this issue open for now still.

I am going to only use email authentication until a fix can be released.
