### ISSUE TITLE
LoginForm.validate() got an unexpected keyword argument 'extra_validators'

### ISSUE THREAD

**Issue by sr-verde** [Flask-Middleware/flask-security#752]
Hey, I am still on Flask-Security 4.1 with one of my projects (don't find the time to upgrade) and now got an error upgrading my dependencies when trying to login.

```
TypeError: LoginForm.validate() got an unexpected keyword argument 'extra_validators'
``` 

This can easily be fixed by pinning Flask-WTF to `< 1.1.0`. I don't know whether this project still "officially" supports its version 4. But the fix would be easy. 

I've fixed it for me in my own requirements specs. So feel free to handle it as you think its reasonable.

**Comment by jwag956** [comment]
Thanks for the note - I do want 4.1.x to still work (and not force folks to upgrade). I'll see if I can spin a quick dot release with this.

**Comment by jwag956** [comment]
Actually - this was fixed in Flask-WTForms 1.1.1 - please try upgrading to that...

https://github.com/wtforms/flask-wtf/issues/547

**Comment by sr-verde** [comment]
I am already running on Flask-WTF 1.1.1.

This is the error I get running tests using pytest:

```
ERROR    myapp:app.py:1744 Exception on /login [POST]
Traceback (most recent call last):
  File "/home/theus/.cache/pypoetry/virtualenvs/myapp-21ts77nC-py3.10/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theus/.cache/pypoetry/virtualenvs/myapp-21ts77nC-py3.10/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theus/.cache/pypoetry/virtualenvs/myapp-21ts77nC-py3.10/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theus/.cache/pypoetry/virtualenvs/myapp-21ts77nC-py3.10/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theus/.cache/pypoetry/virtualenvs/myapp-21ts77nC-py3.10/lib/python3.10/site-packages/flask_security/decorators.py", line 435, in decorated
    return fn(*args, **kwargs)
  File "/home/theus/.cache/pypoetry/virtualenvs/myapp-21ts77nC-py3.10/lib/python3.10/site-packages/flask_security/views.py", line 162, in login
    if form.validate_on_submit():
  File "/home/theus/.cache/pypoetry/virtualenvs/myapp-21ts77nC-py3.10/lib/python3.10/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators=extra_validators)
TypeError: LoginForm.validate() got an unexpected keyword argument 'extra_validators'
``` 

This is `/home/theus/.cache/pypoetry/virtualenvs/myapp-21ts77nC-py3.10/lib/python3.10/site-packages/flask_wtf/form.py`:

```
  82     def validate_on_submit(self, extra_validators=None):                                             
  83         """Call :meth:`validate` only if the form is submitted.                                      
  84         This is a shortcut for ``form.is_submitted() and form.validate()``.                          
  85         """                                                                                          
  86         return self.is_submitted() and self.validate(extra_validators=extra_validators) 
```

So, flask-wtf is fine but all the form classes in Flask Security `form.py` do not have this extra parameter. So, all to be done to fix that is taking and passing all kwargs to the super. I will do that and create a PR for the 4.1.x branch.

**Comment by louking** [comment]
I'm seeing this same behavior with `flask-security-too 5.1.0` and `flask-wtf 1.1.1` for password reset. Should I open a new issue?

```
2023-05-03 11:59:06 ERROR:webmodules:Exception on /account/reset [POST]
2023-05-03 11:59:06 Traceback (most recent call last):
2023-05-03 11:59:06   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
2023-05-03 11:59:06     response = self.full_dispatch_request()
2023-05-03 11:59:06   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
2023-05-03 11:59:06     rv = self.handle_user_exception(e)
2023-05-03 11:59:06   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-05-03 11:59:06     rv = self.dispatch_request()
2023-05-03 11:59:06   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-05-03 11:59:06     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-05-03 11:59:06   File "/usr/local/lib/python3.9/site-packages/flask_security/decorators.py", line 622, in wrapper
2023-05-03 11:59:06     return f(*args, **kwargs)
2023-05-03 11:59:06   File "/usr/local/lib/python3.9/site-packages/flask_security/decorators.py", line 440, in decorated
2023-05-03 11:59:06     return fn(*args, **kwargs)
2023-05-03 11:59:06   File "/usr/local/lib/python3.9/site-packages/flask_security/views.py", line 510, in forgot_password
2023-05-03 11:59:06     if form.validate_on_submit():
2023-05-03 11:59:06   File "/usr/local/lib/python3.9/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
2023-05-03 11:59:06     return self.is_submitted() and self.validate(extra_validators=extra_validators)
2023-05-03 11:59:06 TypeError: validate() got an unexpected keyword argument 'extra_validators'
2023-05-03 11:59:06 INFO:webmodules:192.168.160.5: POST http://app:5000/account/reset 500
```

**Comment by louking** [comment]
ak, sorry for the noise -- I think this is because I have my own validation function which needs to be updated.
